# Generated by Django 3.1.5 on 2021-02-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=145)),
                ('username', models.CharField(max_length=64)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField()),
                ('retweets', models.IntegerField()),
                ('shares', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_text', models.TextField(max_length=255)),
                ('comm_likes', models.IntegerField()),
                ('comm_retweets', models.IntegerField()),
                ('comm_time', models.TimeField(auto_now_add=True)),
                ('comm_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tweet')),
            ],
        ),
    ]
