# Generated by Django 3.1.5 on 2021-02-07 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comm_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comm_retweets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comm_time',
            field=models.TimeField(verbose_name=datetime.datetime(2021, 2, 7, 15, 44, 19, 623019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 15, 44, 19, 621702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
